### ISSUE TITLE
Passing config file as --input_file gives unhelpful error

### ISSUE THREAD

**Issue by leek2** [LLNL/Curvallis#20]
A common mistake a user might make is to pass a config file with --input_file.  Currently that results in an error that doesn't help the user at all.

In the least, this error should be better.  
An even better fix would be to have it autodetect the file type, then do the right thing with it.  So the user wouldn't have to specify input_file or config_file at all.

[leek2@localhost examples]$ ../curvallis.py --input_file=1dexample1.ini 
Current directory is "/home/leek2/prisbrey/Curvallis/examples"
Reading data from "1dexample1.ini"
!!! Warning: File "1dexample1.ini", line 1, "[general]
"
!!! Found non-float string "[general]" - ignored.
!!! Warning: File "1dexample1.ini", line 7, "[inputs]
"
!!! Found non-float string "[inputs]" - ignored.
!!! Warning: File "1dexample1.ini", line 14, "input_file: 1dexample1.dat
"
!!! Found non-float string "input_file:" - ignored.
!!! Warning: File "1dexample1.ini", line 14, "input_file: 1dexample1.dat
"
!!! Found non-float string "1dexample1.dat" - ignored.
!!! Warning: File "1dexample1.ini", line 20, "[outputs]
"
!!! Found non-float string "[outputs]" - ignored.
!!! Warning: File "1dexample1.ini", line 24, "[regions]
"
!!! Found non-float string "[regions]" - ignored.
!!! Warning: File "1dexample1.ini", line 32, "[Shifts, Limits, and Point Exclusion]
"
!!! Found non-float string "[Shifts," - ignored.
!!! Warning: File "1dexample1.ini", line 32, "[Shifts, Limits, and Point Exclusion]
"
!!! Found non-float string "Limits," - ignored.
!!! Warning: File "1dexample1.ini", line 32, "[Shifts, Limits, and Point Exclusion]
"
!!! Found non-float string "and" - ignored.
!!! Warning: File "1dexample1.ini", line 32, "[Shifts, Limits, and Point Exclusion]
"
!!! Found non-float string "Point" - ignored.
!!! Warning: File "1dexample1.ini", line 32, "[Shifts, Limits, and Point Exclusion]
"
!!! Found non-float string "Exclusion]" - ignored.
!!! Warning: File "1dexample1.ini", line 44, "[view]
"
!!! Found non-float string "[view]" - ignored.
!!! Warning: File "1dexample1.ini", line 50, "[fitter]
"
!!! Found non-float string "[fitter]" - ignored.
!!! Warning: File "1dexample1.ini", line 67, "[automatic smoothing]
"
!!! Found non-float string "[automatic" - ignored.
!!! Warning: File "1dexample1.ini", line 67, "[automatic smoothing]
"
!!! Found non-float string "smoothing]" - ignored.
!!! Warning: File "1dexample1.ini", line 80, "; in any column also starts a comment (.ini style)
"
!!! Found non-float string ";" - ignored.
!!! Warning: File "1dexample1.ini", line 80, "; in any column also starts a comment (.ini style)
"
!!! Found non-float string "in" - ignored.
!!! Warning: File "1dexample1.ini", line 80, "; in any column also starts a comment (.ini style)
"
!!! Found non-float string "any" - ignored.
!!! Warning: File "1dexample1.ini", line 80, "; in any column also starts a comment (.ini style)
"
!!! Found non-float string "column" - ignored.
!!! Warning: File "1dexample1.ini", line 80, "; in any column also starts a comment (.ini style)
"
!!! Found non-float string "also" - ignored.
!!! Warning: File "1dexample1.ini", line 80, "; in any column also starts a comment (.ini style)
"
!!! Found non-float string "starts" - ignored.
!!! Warning: File "1dexample1.ini", line 80, "; in any column also starts a comment (.ini style)
"
!!! Found non-float string "a" - ignored.
!!! Warning: File "1dexample1.ini", line 80, "; in any column also starts a comment (.ini style)
"
!!! Found non-float string "comment" - ignored.
!!! Warning: File "1dexample1.ini", line 80, "; in any column also starts a comment (.ini style)
"
!!! Found non-float string "(.ini" - ignored.
!!! Warning: File "1dexample1.ini", line 80, "; in any column also starts a comment (.ini style)
"
!!! Found non-float string "style)" - ignored.
!!! Warning: File "1dexample1.ini", line 81, "--- in the FIRST column starts a comment (.yaml style)
"
!!! Found non-float string "---" - ignored.
!!! Warning: File "1dexample1.ini", line 81, "--- in the FIRST column starts a comment (.yaml style)
"
!!! Found non-float string "in" - ignored.
!!! Warning: File "1dexample1.ini", line 81, "--- in the FIRST column starts a comment (.yaml style)
"
!!! Found non-float string "the" - ignored.
!!! Warning: File "1dexample1.ini", line 81, "--- in the FIRST column starts a comment (.yaml style)
"
!!! Found non-float string "FIRST" - ignored.
!!! Warning: File "1dexample1.ini", line 81, "--- in the FIRST column starts a comment (.yaml style)
"
!!! Found non-float string "column" - ignored.
!!! Warning: File "1dexample1.ini", line 81, "--- in the FIRST column starts a comment (.yaml style)
"
!!! Found non-float string "starts" - ignored.
!!! Warning: File "1dexample1.ini", line 81, "--- in the FIRST column starts a comment (.yaml style)
"
!!! Found non-float string "a" - ignored.
!!! Warning: File "1dexample1.ini", line 81, "--- in the FIRST column starts a comment (.yaml style)
"
!!! Found non-float string "comment" - ignored.
!!! Warning: File "1dexample1.ini", line 81, "--- in the FIRST column starts a comment (.yaml style)
"
!!! Found non-float string "(.yaml" - ignored.
!!! Warning: File "1dexample1.ini", line 81, "--- in the FIRST column starts a comment (.yaml style)
"
!!! Found non-float string "style)" - ignored.
!!! Warning: File "1dexample1.ini", line 102, "[section]      # .ini-style section names are treated as comments
"
!!! Found non-float string "[section]" - ignored.
Lines read: 103
---------------------------------------------------------------
input points: 1dexample1.ini:
Number of points: 0
---------------------------------------------------------------
inf -inf inf -inf
Traceback (most recent call last):
  File "../curvallis.py", line 18, in <module>
    main()
  File "/home/leek2/prisbrey/Curvallis/curvallis/run.py", line 784, in main
    CurveInteractor().run()
  File "/home/leek2/prisbrey/Curvallis/curvallis/run.py", line 151, in run
    self._setup_GUI()
  File "/home/leek2/prisbrey/Curvallis/curvallis/run.py", line 189, in _setup_GUI
    self._set_xlim_ylim()
  File "/home/leek2/prisbrey/Curvallis/curvallis/run.py", line 271, in _set_xlim_ylim
    self._ax.set_xlim(xmin_data, xmax_data)
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes/_base.py", line 3139, in set_xlim
    left = self._validate_converted_limits(left, self.convert_xunits)
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes/_base.py", line 3068, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf

**Comment by nprisbrey** [comment]
@leek2, from what I've been able to infer, normally a user can only list one config file max into the --config_file argument and only one input file max into the --input_file argument, correct? If these two command line arguments are to be combined, should the argument be able to receive an input file and a config file in the SAME run or does the user have to choose between giving Curvallis an input OR config file?

**Comment by leek2** [comment]
Good point.  Normally the config file also contains the input file.  However, being able to supply both on the same command line is handy in some cases.  e.g. you have a basic configuration you want to apply to multiple different input files for comparison.  (The current behavior allows this.)

If it's not too complex, I would allow both arguments.
1. Only --input_file is supplied, it could be an input file or config file.  Autodetect.  But a warning is printed if it's actually a config file.
2. Only --config_file is supplied, it could be an input file or config file.  Autodetect. But a warning is printed if it's actually an input file.
3. If both are supplied either do:
  a. They should both be correct, print an error and quit if not.
  b. They can be wrong, but you must have one of each.  And a warning is printed.  If you get 2 of one type, and error is printed and quit.

I think either 3a or 3b would be fine.  Whichever is easier to implement.
* Or if all are these options are too hard, just stick with the current system and print an intelligible error and quit if the incorrect file types are supplied.

**Comment by leek2** [comment]
BTW, This isn't done yet
